#spring:
#  datasource:
##    url: jdbc:mysql://currency-exchange.c3c8ckog2bm2.us-east-2.rds.amazonaws.com:3306/currency_exchange
##    username: admin
##    password: xWD6JXSxWi3UxcBOPId8
#     url: jdbc:mysql://localhost:3306/Curr_Conv_DB?useSSL=false
#     username: root
#     password: Swaminarayan@6
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
